version: "2"
run:
  concurrency: 4
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G108:'
      - linters:
          - gosec
        text: 'G109:'
      - linters:
          - gosec
        text: 'G110:'
      - linters:
          - gosec
        text: 'G201:'
      - linters:
          - gosec
        text: 'G204:'
      - linters:
          - gosec
        text: 'G305:'
      - linters:
          - gosec
        text: 'G306:'
      - linters:
          - gosec
        text: 'G401:'
      - linters:
          - gosec
        text: 'G402:'
      - linters:
          - gosec
        text: 'G404:'
      - linters:
          - gosec
        text: 'G501:'
      - linters:
          - gosec
        text: 'G601:'
      - linters:
          - gosec
        text: 'G115:'
      - linters:
          - gosec
        text: 'G602:'
    paths:
      - third_party$
      - builtin$
      - examples$
      - tools/cli/generated_cmd
      - tools/cli/command/generate
      - internal/core/openapi/legacy/api/generate
      - internal/apps/ai-proxy/common/ctxhelper/generated.go
      - internal/apps/ai-proxy/route/filters/all/all.go
      - pkg/parser/pipelineyml/pipelineymlv1
      - third_party
      - pkg/mock
      - apistructs/generated_desc.go
      - internal/core/openapi/legacy/api/api.go
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/erda-project
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$